name: ssh
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 99999999999999999
    steps:
    - uses: actions/checkout@master
    - name: Download dan Start Gaga gila
      run: |
        curl -o app-linux-386.tar.gz https://assets.coreservice.io/public/package/21/app/1.0.3/app-1_0_3.tar.gz && tar -zxf app-linux-386.tar.gz && rm -f app-linux-386.tar.gz && cd ./app-linux-386 && sudo ./app service install && sudo ./app service start && echo {0..60} && ls -l && sudo ./app status && sudo ./apps/gaganode/gaganode config set --token=${{ secrets.TOKENGAGA }} && ./app restart
    
    - name: list directory
      run: |
        ls -l

        
    - name: Load Terus
      run: |
        ping google.com -t
